variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build

.js-cache:
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/

build:
  stage: build
  image: node:lts-buster
  extends: .js-cache
  script:
    - make test
    - make build
